#数据库配置
#spring:
#  datasource:
#    url: jdbc:mysql://o186928x99.imwork.net:12921/brian?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver

#多数据源配置
#spring:
mysql:
  datasource:
    kawa: #数据源1
     # url: jdbc:mysql://o186928x99.imwork.net:12921/brian?useUnicode=true&characterEncoding=utf-8&useSSL=false
      jdbc-url: jdbc:mysql://xuduocloud.qicp.vip:14110/brian?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: XXXXX
      driver-class-name: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    kawa02: #数据源2
#      jdbc-url: jdbc:mysql://remotemysql.com:3306/khgvUiO4eh?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: khgvUiO4eh
#      password: BGAAee478r
      jdbc-url: jdbc:mysql://xuduocloud.qicp.vip:14110/brian02?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: XXXXX
      driver-class-name: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60


spring:
#配置redis数据库
  redis:
    host: 10.0.75.1
#配置rabbitMQ
  rabbitmq:
    host: 10.0.75.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #值为true可实现消息确认
    publisher-confirms: true
#配置r2dbc + postgresql
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: Chen@2019
   #配置邮件
  mail:
    username: 1092249319@qq.com
    password: xxxxxxxxxxxxxxxxx
    host: smtp.qq.com
    #开启ssl安全协议(不开启报错连接超时)
    properties:
     mail:
      smtp:
       ssl:
        enable: true
#服务名
  application:
    name: brian-query-service

#eureka主机名，会在控制页面中显示
eureka:
#eureka注册中心服务器地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/




